import React, { useState, useEffect, useMemo } from 'react';
import { Users, Search, Edit2, Trash2, X, AlertCircle, CheckCircle2, UserPlus, Eye, Check, AlertTriangle, ChevronLeft, ChevronRight } from 'lucide-react';
import { invoke } from '@tauri-apps/api/core';

const visitorYearCode = new Date().getFullYear().toString().slice(-2);

const ID_NUMBER_RULES = {
    student: {
        placeholder: '00-00000',
        pattern: /^\d{2}-\d{5}$/,
        hint: 'Student IDs must follow the 00-00000 format.',
        maxLength: 8,
    },
    professor: {
        placeholder: '0000000',
        pattern: /^\d{7}$/,
        hint: 'Professor IDs must be exactly 7 digits.',
        maxLength: 7,
    },
    staff: {
        placeholder: '0000000',
        pattern: /^\d{7}$/,
        hint: 'Staff IDs must be exactly 7 digits.',
        maxLength: 7,
    },
    visitor: {
        placeholder: `VIS-${visitorYearCode}xxxx`,
        pattern: new RegExp(`^VIS-${visitorYearCode}\\d{4}$`),
        hint: `Visitor IDs must follow the VIS-${visitorYearCode}xxxx format.`,
        maxLength: 10,
    },
};

const trimToNull = (value) => {
    if (typeof value !== 'string') return null;
    const trimmed = value.trim();
    return trimmed ? trimmed : null;
};

const buildUserPayload = (role, data) => ({
    role,
    idNumber: (data.id_number || '').trim(),
    firstName: (data.first_name || '').trim(),
    middleName: trimToNull(data.middle_name),
    lastName: (data.last_name || '').trim(),
    email: trimToNull(data.email),
    contactNumber: trimToNull(data.contact_number),
    programId: role === 'student' && data.program_id ? parseInt(data.program_id, 10) : null,
    yearLevel: role === 'student' && data.year_level ? parseInt(data.year_level, 10) : null,
    departmentId: (role === 'professor' || role === 'staff') && data.department_id ? parseInt(data.department_id, 10) : null,
    positionTitle: role === 'professor' || role === 'staff' ? trimToNull(data.position_title) : null,
    purpose: role === 'visitor' ? trimToNull(data.purpose_of_visit) : null,
    personToVisit: role === 'visitor' ? trimToNull(data.person_to_visit) : null,
    idPresented: role === 'visitor' ? trimToNull(data.id_presented) : null,
});

export const UserManagement = ({ adminSession }) => {
    const isSystemAdministrator = adminSession?.role === 'System Administrator';
    const [mainTab, setMainTab] = useState('members'); // 'members', 'visitors'
    const [subTab, setSubTab] = useState('student'); // 'student', 'professor', 'staff'
    const activeRole = mainTab === 'visitors' ? 'visitor' : subTab;

    const [searchQuery, setSearchQuery] = useState('');
    const [users, setUsers] = useState([]);
    const [departments, setDepartments] = useState([]);
    const [programs, setPrograms] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    // Modal States
    const [showRegisterModal, setShowRegisterModal] = useState(false);
    const [showEditModal, setShowEditModal] = useState(false);
    const [showDeleteModal, setShowDeleteModal] = useState(false);
    const [showViewModal, setShowViewModal] = useState(false);
    const [selectedUser, setSelectedUser] = useState(null);
    const [status, setStatus] = useState(null);
    const [isEmailAutoGenerated, setIsEmailAutoGenerated] = useState(true);

    // Form State
    const [formData, setFormData] = useState({
        role: 'student',
        id_number: '',
        first_name: '',
        middle_name: '',
        last_name: '',
        program_id: '',
        department_id: '',
        year_level: '',
        position_title: '',
        email: '',
        contact_number: '',
        id_presented: '',
        purpose_of_visit: '',
        person_to_visit: '',
        is_active: true,
    });

    // Auto-generate email when name changes and isEmailAutoGenerated is true
    useEffect(() => {
        if (isEmailAutoGenerated && (formData.role === 'student' || formData.role === 'professor' || formData.role === 'staff')) {
            const first = (formData.first_name || '').trim().toLowerCase().replace(/\s+/g, '');
            const last = (formData.last_name || '').trim().toLowerCase().replace(/\s+/g, '');
            if (first || last) {
                let generated = '';
                if (first && last) generated = `${last}_${first}@plpasig.edu.ph`;
                else if (first) generated = `${first}@plpasig.edu.ph`;
                else generated = `${last}@plpasig.edu.ph`;
                setFormData(prev => ({ ...prev, email: generated }));
            } else {
                setFormData(prev => ({ ...prev, email: '' }));
            }
        }
    }, [formData.first_name, formData.last_name, isEmailAutoGenerated, formData.role]);

    const fetchUsers = async () => {
        setIsLoading(true);
        try {
            if (mainTab === 'visitors') {
                const data = await invoke('get_visitors');
                setUsers(data);
            } else if (subTab === 'student') {
                const data = await invoke('get_students');
                setUsers(data);
            } else {
                const data = await invoke('get_employees');
                setUsers(data.filter(emp =>
                    subTab === 'professor' ? emp.position_title.toLowerCase().includes('prof') : !emp.position_title.toLowerCase().includes('prof')
                ));
            }
        } catch (error) {
            console.error(error);
            setStatus({ type: 'error', message: 'Failed to fetch users.' });
        } finally {
            setIsLoading(false);
        }
    };

    const fetchSelectData = async () => {
        try {
            const deps = await invoke('get_departments');
            const progs = await invoke('get_programs');
            setDepartments(deps);
            setPrograms(progs);
        } catch (e) {
            console.error("Failed to load departments/programs", e);
        }
    };

    useEffect(() => {
        fetchSelectData();
    }, []);

    useEffect(() => {
        fetchUsers();
    }, [mainTab, subTab]);

    const activeIdRule = ID_NUMBER_RULES[formData.role];
    const trimmedIdNumber = (formData.id_number || '').trim();
    const isIdNumberValid = activeIdRule.pattern.test(trimmedIdNumber);
    const idNumberValidationMessage = trimmedIdNumber && !isIdNumberValid ? activeIdRule.hint : '';

    const handleRegisterSubmit = async (e) => {
        e.preventDefault();
        try {
            const payload = buildUserPayload(formData.role, formData);
            const personId = await invoke('register_user', payload);

            if (formData.role !== 'visitor' && !formData.is_active) {
                await invoke('update_person_status', {
                    personId,
                    isActive: false,
                });
            }

            setStatus({ type: 'success', message: 'User registered successfully!' });
            setShowRegisterModal(false);
            fetchUsers();
        } catch (error) {
            console.error(error);
            setStatus({ type: 'error', message: typeof error === 'string' ? error : 'Failed to register user.' });
        }
    };

    const handleEditClick = (user) => {
        setSelectedUser(user);
        setFormData({
            role: activeRole,
            id_number: user.id_number || '',
            first_name: user.first_name || '',
            middle_name: user.middle_name || '',
            last_name: user.last_name || '',
            program_id: user.program_id ? user.program_id.toString() : (programs.length > 0 ? programs[0].program_id.toString() : ''),
            department_id: user.department_id ? user.department_id.toString() : (departments.length > 0 ? departments[0].department_id.toString() : ''),
            year_level: user.year_level ? user.year_level.toString() : '',
            position_title: user.position_title || '',
            email: user.email || '',
            contact_number: user.contact_number || '',
            id_presented: user.id_presented || '',
            purpose_of_visit: user.purpose_of_visit || '',
            person_to_visit: user.person_to_visit || '',
            is_active: user.is_active ?? true,
        });
        setIsEmailAutoGenerated(!user.email);
        setShowEditModal(true);
    };

    const handleEditSubmit = async (e) => {
        e.preventDefault();
        try {
            const payload = buildUserPayload(activeRole, formData);

            await invoke('update_user', {
                personId: selectedUser.person_id,
                ...payload,
            });

            if (activeRole !== 'visitor') {
                await invoke('update_person_status', {
                    personId: selectedUser.person_id,
                    isActive: formData.is_active,
                });
            }

            setStatus({ type: 'success', message: 'User updated successfully!' });
            setShowEditModal(false);
            fetchUsers();
        } catch (error) {
            console.error(error);
            setStatus({ type: 'error', message: typeof error === 'string' ? error : 'Failed to update user.' });
        }
    };

    const handleDeleteClick = (user) => {
        setSelectedUser(user);
        setShowDeleteModal(true);
    };

    const confirmDelete = async () => {
        try {
            await invoke('delete_user', {
                personId: selectedUser.person_id,
                role: activeRole
            });
            setStatus({ type: 'success', message: 'User deleted successfully!' });
            setShowDeleteModal(false);
            fetchUsers();
        } catch (error) {
            console.error(error);
            setStatus({ type: 'error', message: typeof error === 'string' ? error : 'Failed to delete user.' });
        }
    };

    const handleRegisterClick = () => {
        setFormData({
            role: activeRole,
            id_number: '',
            first_name: '',
            middle_name: '',
            last_name: '',
            program_id: programs.length > 0 ? programs[0].program_id.toString() : '',
            department_id: departments.length > 0 ? departments[0].department_id.toString() : '',
            year_level: '',
            position_title: '',
            email: '',
            contact_number: '',
            id_presented: '',
            purpose_of_visit: '',
            person_to_visit: '',
            is_active: true,
        });
        setStatus(null);
        setIsEmailAutoGenerated(true);
        setShowRegisterModal(true);
    };

    const handleViewClick = (user) => {
        setSelectedUser(user);
        setShowViewModal(true);
    };

    // Filter logic
    const filteredUsers = users.filter(user =>
        (user.first_name + ' ' + (user.last_name || '')).toLowerCase().includes(searchQuery.toLowerCase()) ||
        (user.id_number || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
        (user.id_presented || '').toLowerCase().includes(searchQuery.toLowerCase())
    );

    // Pagination
    const ITEMS_PER_PAGE = 15;
    const [currentPage, setCurrentPage] = useState(1);
    useEffect(() => { setCurrentPage(1); }, [searchQuery, mainTab, subTab]);
    const totalPages = Math.ceil(filteredUsers.length / ITEMS_PER_PAGE);
    const paginatedUsers = useMemo(() => {
        const start = (currentPage - 1) * ITEMS_PER_PAGE;
        return filteredUsers.slice(start, start + ITEMS_PER_PAGE);
    }, [filteredUsers, currentPage]);
    const showPagination = filteredUsers.length > ITEMS_PER_PAGE;

    return (
        <div className="w-full h-full min-h-0 space-y-6 animate-in slide-in-from-bottom-4 duration-500 relative flex flex-col">
            {/* Status Toast */}
            {status && (
                <div className="absolute top-0 left-1/2 transform -translate-x-1/2 z-50 w-full max-w-md px-4">
                    <div className={`p-4 rounded-xl flex items-center justify-between gap-4 shadow-lg border ${status.type === 'success' ? 'bg-emerald-50 text-emerald-800 border-emerald-200' : 'bg-rose-50 text-rose-800 border-rose-200'
                        }`}>
                        <div className="flex items-center gap-3">
                            {status.type === 'success' ? <CheckCircle2 className="w-5 h-5 text-emerald-600" /> : <AlertCircle className="w-5 h-5 text-rose-600" />}
                            <span className="font-medium text-sm">{status.message}</span>
                        </div>
                        <button onClick={() => setStatus(null)}><X className="w-5 h-5 hover:text-slate-500" /></button>
                    </div>
                </div>
            )}

            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 mb-2">User Registry</h1>
                    <p className="text-slate-500">Manage students, professors, staff, and visitors.</p>
                </div>
                {isSystemAdministrator && (
                    <button
                        onClick={handleRegisterClick}
                        className="flex items-center gap-2 bg-blue-600 text-white hover:bg-blue-700 px-5 py-2.5 rounded-xl font-bold shadow-sm transition-all focus:outline-none focus:ring-4 focus:ring-blue-500/30"
                    >
                        <UserPlus className="w-5 h-5" /> Register Profile
                    </button>
                )}
            </div>

            {/* Controls: Tabs & Search */}
            <div className="p-3 bg-white rounded-2xl border border-slate-200 shadow-sm flex flex-col gap-4">
                <div className="flex flex-col lg:flex-row justify-between items-center gap-4">
                    <div className="flex gap-2 p-1 bg-slate-100 rounded-xl">
                        {['members', 'visitors'].map((tab) => (
                            <button
                                key={tab}
                                onClick={() => setMainTab(tab)}
                                className={`px-6 py-2.5 rounded-lg font-medium capitalize transition-all duration-300 ${mainTab === tab
                                    ? 'bg-white text-slate-900 shadow-sm border border-slate-200'
                                    : 'text-slate-500 hover:text-slate-900 hover:bg-slate-200/50'
                                    }`}
                            >
                                {tab === 'members' ? 'University Members' : 'Visitors'}
                            </button>
                        ))}
                    </div>

                    <div className="relative w-full lg:w-1/3">
                        <Search className="w-5 h-5 absolute left-4 top-1/2 transform -translate-y-1/2 text-slate-400" />
                        <input
                            type="text"
                            placeholder="Search by ID or Name..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-11 pr-4 py-2.5 text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500/50 transition-all font-medium"
                        />
                    </div>
                </div>

                {mainTab === 'members' && (
                    <div className="flex gap-2">
                        {['student', 'professor', 'staff'].map((tab) => (
                            <button
                                key={tab}
                                onClick={() => setSubTab(tab)}
                                className={`px-4 py-1.5 rounded-full text-sm font-semibold capitalize transition-all duration-300 ${subTab === tab
                                    ? 'bg-blue-100 text-blue-700 border border-blue-200'
                                    : 'text-slate-500 hover:bg-slate-100 hover:text-slate-800'
                                    }`}
                            >
                                {tab}s
                            </button>
                        ))}
                    </div>
                )}
            </div>

            {/* Data Table - scroll container with sticky headers */}
            <div className="flex-1 min-h-0 flex flex-col bg-white border border-slate-200 rounded-xl shadow-sm relative">
                <div className="flex-1 min-h-0 overflow-x-auto overflow-y-auto">
                    <table className="w-full text-left text-sm text-slate-600">
                        <thead className="text-xs uppercase bg-slate-100 border-b border-slate-200 text-slate-700 sticky top-0 z-10">
                            <tr>
                                <th className="px-6 py-4 font-semibold tracking-wider">ID Number</th>
                                <th className="px-6 py-4 font-semibold tracking-wider">Full Name</th>
                                {mainTab === 'visitors' ? (
                                    <>
                                        <th className="px-6 py-4 font-semibold tracking-wider">Purpose</th>
                                        <th className="px-6 py-4 font-semibold tracking-wider">Person to Visit</th>
                                        <th className="px-6 py-4 font-semibold tracking-wider">Registration Date</th>
                                        <th className="px-6 py-4 font-semibold tracking-wider">Registration Time</th>
                                    </>
                                ) : (
                                    <>
                                        <th className="px-6 py-4 font-semibold tracking-wider">
                                            {subTab === 'student' ? 'Program / Year' : 'Department'}
                                        </th>
                                        <th className="px-6 py-4 font-semibold tracking-wider">Status</th>
                                    </>
                                )}
                                <th className="px-6 py-4 font-semibold tracking-wider text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {isLoading ? (
                                <tr>
                                    <td colSpan={mainTab === 'visitors' ? 7 : 5} className="text-center py-20 text-slate-500">Loading data...</td>
                                </tr>
                            ) : filteredUsers.length === 0 ? (
                                <tr>
                                    <td colSpan={mainTab === 'visitors' ? 7 : 5} className="text-center py-20">
                                        <div className="flex flex-col items-center justify-center space-y-3">
                                            <Users className="w-12 h-12 text-slate-300" />
                                            <p className="text-slate-500 text-base">No {activeRole}s found.</p>
                                        </div>
                                    </td>
                                </tr>
                            ) : (
                                paginatedUsers.map((user) => (
                                    <tr key={user.person_id} className="hover:bg-slate-50 even:bg-slate-50/50 transition-colors group">
                                        <td className="px-6 py-4 font-mono font-medium text-slate-900">{user.id_number}</td>
                                        <td className="px-6 py-4 font-medium text-slate-900">{user.first_name} {user.last_name || ''}</td>
                                        {mainTab === 'visitors' ? (
                                            <>
                                                <td className="px-6 py-4 text-slate-600">{user.purpose_of_visit}</td>
                                                <td className="px-6 py-4 text-slate-600">{user.person_to_visit || 'N/A'}</td>
                                                <td className="px-6 py-4 text-slate-600">
                                                    {user.time_in ? new Date(user.time_in).toLocaleDateString() : 'N/A'}
                                                </td>
                                                <td className="px-6 py-4 text-slate-600">
                                                    {user.time_in ? new Date(user.time_in).toLocaleTimeString([], { timeStyle: 'short' }) : 'N/A'}
                                                </td>
                                            </>
                                        ) : (
                                            <>
                                                <td className="px-6 py-4 text-slate-600">
                                                    {subTab === 'student'
                                                        ? `${user.program_name} ${user.year_level ? `- Yr ${user.year_level}` : ''}`
                                                        : `${user.department_name || 'N/A'} - ${user.position_title}`}
                                                </td>
                                                <td className="px-6 py-4">
                                                    <span className={`px-2.5 py-1 text-xs font-semibold rounded-full ${user.is_active ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' : 'bg-rose-100 text-rose-700 border border-rose-200'
                                                        }`}>
                                                        {user.is_active ? 'Active' : 'Inactive'}
                                                    </span>
                                                </td>
                                            </>
                                        )}
                                        <td className="px-6 py-4 text-right space-x-2">
                                            <button
                                                className="p-2 text-blue-600 hover:bg-blue-100 rounded-lg transition-colors border border-transparent hover:border-blue-200 opacity-0 group-hover:opacity-100 focus:opacity-100"
                                                title="View Details"
                                                onClick={() => handleViewClick(user)}>
                                                <Eye className="w-4 h-4" />
                                            </button>
                                            {isSystemAdministrator && (
                                                <>
                                                    <button className="p-2 text-amber-600 hover:bg-amber-100 rounded-lg transition-colors border border-transparent hover:border-amber-200 opacity-0 group-hover:opacity-100 focus:opacity-100" title="Edit"
                                                        onClick={() => handleEditClick(user)}>
                                                        <Edit2 className="w-4 h-4" />
                                                    </button>
                                                    <button className="p-2 text-rose-600 hover:bg-rose-100 rounded-lg transition-colors border border-transparent hover:border-rose-200 opacity-0 group-hover:opacity-100 focus:opacity-100" title="Delete"
                                                        onClick={() => handleDeleteClick(user)}>
                                                        <Trash2 className="w-4 h-4" />
                                                    </button>
                                                </>
                                            )}
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Pagination footer (only when records > items per page) */}
                {showPagination && (
                    <div className="px-6 py-3 border-t border-slate-200 bg-slate-50 text-xs font-semibold text-slate-500 flex flex-wrap items-center justify-between gap-3 shrink-0 rounded-b-xl">
                        <div>
                            Showing {(currentPage - 1) * ITEMS_PER_PAGE + 1}–{Math.min(currentPage * ITEMS_PER_PAGE, filteredUsers.length)} of {filteredUsers.length}
                        </div>
                        <div className="flex items-center gap-1">
                            <button
                                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                                disabled={currentPage === 1}
                                className="px-2 py-1 rounded border border-slate-200 bg-white disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50 transition-colors flex items-center gap-0.5"
                            >
                                <ChevronLeft className="w-4 h-4" /> Previous
                            </button>
                            {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
                                <button
                                    key={p}
                                    onClick={() => setCurrentPage(p)}
                                    className={`min-w-[28px] px-2 py-1 rounded border transition-colors ${currentPage === p
                                        ? 'bg-slate-800 text-white border-slate-800'
                                        : 'border-slate-200 bg-white hover:bg-slate-50'
                                        }`}
                                >
                                    {p}
                                </button>
                            ))}
                            <button
                                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                                disabled={currentPage === totalPages}
                                className="px-2 py-1 rounded border border-slate-200 bg-white disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50 transition-colors flex items-center gap-0.5"
                            >
                                Next <ChevronRight className="w-4 h-4" />
                            </button>
                        </div>
                    </div>
                )}
            </div>

            {/* Smart Registration / Edit Form Component */}
            {(showRegisterModal || showEditModal) && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-md p-4 animate-in fade-in">
                    <div className="bg-black/90 backdrop-blur-3xl border border-white/20 rounded-3xl shadow-2xl w-full max-w-2xl overflow-y-auto max-h-[90vh] animate-in zoom-in-95 duration-200">
                        <div className="px-8 py-6 border-b border-white/10 flex justify-between items-center sticky top-0 bg-black/50 backdrop-blur-md z-10">
                            <div className="flex items-center gap-3">
                                <div className={`p-2 bg-white/10 rounded-lg border border-white/20 `}>
                                    {showEditModal ? <Edit2 className="w-5 h-5 text-amber-400" /> : <UserPlus className="w-5 h-5 text-emerald-400" />}
                                </div>
                                <h2 className="text-xl font-bold text-white tracking-wide">{showEditModal ? 'Edit Profile' : 'Register New Profile'}</h2>
                            </div>
                            <button onClick={() => { setShowRegisterModal(false); setShowEditModal(false); }} className="text-white/50 hover:text-white transition-colors bg-white/5 p-2 rounded-xl hover:bg-white/10"><X className="w-5 h-5" /></button>
                        </div>

                        <form onSubmit={showEditModal ? handleEditSubmit : handleRegisterSubmit} className="p-8 space-y-8">
                            {/* Role Selector (Only in Register mode to prevent changing role of existing user easily) */}
                            {!showEditModal && mainTab === 'members' && (
                                <div className="space-y-3">
                                    <label className="block text-sm font-semibold text-white/80">Select Role</label>
                                    <div className="flex gap-3">
                                        {['student', 'professor', 'staff'].map((r) => (
                                            <label key={r} className={`flex-1 flex items-center justify-center gap-2 p-3 rounded-xl border cursor-pointer transition-all ${formData.role === r ? 'bg-blue-600/20 border-blue-500 text-blue-400' : 'bg-black/40 border-white/10 text-white/50 hover:border-white/30'}`}>
                                                <input type="radio" name="role" value={r} checked={formData.role === r} onChange={(e) => setFormData({ ...formData, role: e.target.value })} className="sr-only" />
                                                <span className="capitalize font-medium">{r}</span>
                                            </label>
                                        ))}
                                    </div>
                                </div>
                            )}

                            <div className="space-y-6">
                                <div className="space-y-4">
                                    <div>
                                        <label className="block text-xs text-white/60 mb-1 font-medium">
                                            {formData.role === 'student' ? 'Student ID Number' : formData.role === 'visitor' ? 'Visitor ID Number' : 'ID Number'} <span className="text-rose-500 text-base font-bold ml-0.5">*</span>
                                        </label>
                                        <input
                                            required
                                            type="text"
                                            inputMode={formData.role === 'visitor' ? 'text' : 'numeric'}
                                            value={formData.id_number}
                                            maxLength={activeIdRule.maxLength}
                                            onChange={e => setFormData({
                                                ...formData,
                                                id_number: formData.role === 'visitor' ? e.target.value.toUpperCase() : e.target.value,
                                            })}
                                            className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-white font-mono placeholder-white/20 focus:ring-2 focus:outline-none transition-all ${idNumberValidationMessage ? 'border-rose-400/70 focus:ring-rose-500/40 focus:border-rose-400' : 'border-white/10 focus:ring-blue-500/50 focus:border-blue-500/50'}`}
                                            placeholder={activeIdRule.placeholder}
                                        />
                                        <p className={`mt-2 text-xs font-medium transition-colors ${idNumberValidationMessage ? 'text-rose-300' : 'text-white/45'}`}>
                                            {idNumberValidationMessage || activeIdRule.hint}
                                        </p>
                                    </div>

                                    <div className="grid grid-cols-1 items-start gap-4 md:grid-cols-3">
                                        <div className="flex min-w-0 w-full flex-col">
                                            <label className="mb-1 flex min-h-[20px] items-end text-xs font-medium text-white/60">First Name <span className="ml-0.5 text-base font-bold text-rose-500">*</span></label>
                                            <input required type="text" value={formData.first_name} onChange={e => setFormData({ ...formData, first_name: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                        <div className="flex min-w-0 w-full flex-col">
                                            <label className="mb-1 flex min-h-[24px] items-end text-xs font-medium text-white/60">Middle Name</label>
                                            <input type="text" value={formData.middle_name} onChange={e => setFormData({ ...formData, middle_name: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                        <div className="flex min-w-0 w-full flex-col">
                                            <label className="mb-1 flex min-h-[20px] items-end text-xs font-medium text-white/60">Last Name <span className="ml-0.5 text-base font-bold text-rose-500">*</span></label>
                                            <input required type="text" value={formData.last_name} onChange={e => setFormData({ ...formData, last_name: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Email Address</label>
                                            <input type="email" value={formData.email} onChange={e => { setIsEmailAutoGenerated(false); setFormData({ ...formData, email: e.target.value }); }} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Contact Number</label>
                                            <input type="text" value={formData.contact_number} onChange={e => setFormData({ ...formData, contact_number: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white font-mono focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                    </div>
                                </div>

                                <div className="h-px w-full bg-white/5 my-6"></div>

                                {formData.role === 'student' && (
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 animate-in fade-in">
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Program <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <select required value={formData.program_id} onChange={e => setFormData({ ...formData, program_id: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none appearance-none">
                                                {programs.length === 0 && <option value="" disabled>No Programs Available</option>}
                                                {programs.map(p => (
                                                    <option key={p.program_id} value={p.program_id} className="bg-slate-900">{p.program_code} - {p.program_name}</option>
                                                ))}
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Year Level <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <select required value={formData.year_level} onChange={e => setFormData({ ...formData, year_level: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none appearance-none">
                                                <option value="" disabled className="bg-slate-900">Select Year Level</option>
                                                <option value="1" className="bg-slate-900">1st Year</option>
                                                <option value="2" className="bg-slate-900">2nd Year</option>
                                                <option value="3" className="bg-slate-900">3rd Year</option>
                                                <option value="4" className="bg-slate-900">4th Year</option>
                                                <option value="5" className="bg-slate-900">5th Year</option>
                                            </select>
                                        </div>
                                    </div>
                                )}

                                {(formData.role === 'professor' || formData.role === 'staff') && (
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 animate-in fade-in">
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Department <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <select required value={formData.department_id} onChange={e => setFormData({ ...formData, department_id: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none appearance-none">
                                                {departments.length === 0 && <option value="" disabled>No Departments Available</option>}
                                                {departments.map(d => (
                                                    <option key={d.department_id} value={d.department_id} className="bg-slate-900">{d.department_code} - {d.department_name}</option>
                                                ))}
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Designation / Title <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <input required type="text" value={formData.position_title} onChange={e => setFormData({ ...formData, position_title: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" placeholder="e.g. Associate Professor" />
                                        </div>
                                    </div>
                                )}

                                {formData.role === 'visitor' && (
                                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 animate-in fade-in">
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Purpose of Visit <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <input required type="text" value={formData.purpose_of_visit} onChange={e => setFormData({ ...formData, purpose_of_visit: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                        <div>
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Person to Visit <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <input required type="text" value={formData.person_to_visit} onChange={e => setFormData({ ...formData, person_to_visit: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                        <div className="md:col-span-2">
                                            <label className="block text-xs text-white/60 mb-1 font-medium">Presented ID Type/Number <span className="text-rose-500 text-base font-bold ml-0.5">*</span></label>
                                            <input required type="text" value={formData.id_presented} onChange={e => setFormData({ ...formData, id_presented: e.target.value })} className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white font-mono focus:ring-2 focus:ring-white/20 focus:outline-none" />
                                        </div>
                                    </div>
                                )}

                                {formData.role !== 'visitor' && (
                                    <div className="flex items-center gap-3 mt-4 p-4 bg-white/5 border border-white/10 rounded-xl">
                                        <input type="checkbox" id="isActive" checked={formData.is_active} onChange={e => setFormData({ ...formData, is_active: e.target.checked })} className="w-5 h-5 text-emerald-500 bg-black/50 border-white/20 rounded focus:ring-emerald-500/50" />
                                        <label htmlFor="isActive" className="text-sm font-medium text-white">ID Card Active (Allowed Entry)</label>
                                    </div>
                                )}
                            </div>

                            <div className="pt-6">
                                <button
                                    type="submit"
                                    disabled={!isIdNumberValid}
                                    className={`w-full ${showEditModal ? 'bg-amber-500 hover:bg-amber-400 text-black shadow-[0_0_20px_rgba(245,158,11,0.2)] hover:shadow-[0_0_30px_rgba(245,158,11,0.4)]' : 'bg-emerald-500 hover:bg-emerald-400 text-black shadow-[0_0_20px_rgba(16,185,129,0.2)] hover:shadow-[0_0_30px_rgba(16,185,129,0.4)]'} font-bold text-lg py-4 rounded-xl transition-all focus:outline-none focus:ring-4 focus:ring-white/40 flex justify-center items-center gap-2 hover:scale-[1.01] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:scale-100 disabled:shadow-none`}
                                >
                                    <Check className="w-6 h-6" /> {showEditModal ? 'Save Changes' : 'Confirm & Register'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Delete Confirmation Modal */}
            {showDeleteModal && selectedUser && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-md p-4 animate-in fade-in">
                    <div className="bg-rose-950/40 backdrop-blur-2xl border border-rose-500/30 rounded-3xl shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-200">
                        <div className="p-8 flex flex-col items-center text-center space-y-6">
                            <div className="w-20 h-20 bg-rose-500/20 rounded-full flex items-center justify-center border-4 border-rose-500/30">
                                <AlertTriangle className="w-10 h-10 text-rose-400" />
                            </div>
                            <div className="space-y-2">
                                <h2 className="text-2xl font-bold text-white">Delete Profile?</h2>
                                <p className="text-white/70">Are you sure you want to permanently delete <span className="text-white font-semibold">{selectedUser.first_name} {selectedUser.last_name}</span>? This action cannot be undone.</p>
                            </div>
                            <div className="flex gap-4 w-full pt-4">
                                <button onClick={() => setShowDeleteModal(false)} className="flex-1 py-3 px-4 bg-white/5 hover:bg-white/10 text-white font-semibold rounded-xl transition-colors border border-white/10 focus:outline-none">Cancel</button>
                                <button onClick={confirmDelete} className="flex-1 py-3 px-4 bg-rose-500 hover:bg-rose-600 text-white font-bold rounded-xl transition-all shadow-[0_0_20px_rgba(244,63,94,0.3)] hover:shadow-[0_0_30px_rgba(244,63,94,0.5)] border border-rose-400 focus:outline-none">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* View Details Modal */}
            {showViewModal && selectedUser && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-md p-4 animate-in fade-in">
                    <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-200">
                        <div className="bg-slate-50 border-b border-slate-200 p-6 flex justify-between items-center">
                            <h2 className="text-xl font-bold text-slate-900">Profile Details</h2>
                            <button onClick={() => setShowViewModal(false)} className="text-slate-400 hover:bg-slate-200 hover:text-slate-600 p-2 rounded-xl transition-colors"><X className="w-5 h-5" /></button>
                        </div>
                        <div className="p-6 space-y-6">
                            <div className="flex items-center gap-4 border-b border-slate-100 pb-6">
                                <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 text-2xl font-bold">
                                    {selectedUser.first_name.charAt(0)}
                                </div>
                                <div>
                                    <h3 className="text-lg font-bold text-slate-900">{selectedUser.first_name} {selectedUser.middle_name} {selectedUser.last_name || ''}</h3>
                                    <p className="text-sm font-mono text-slate-500">{selectedUser.id_number}</p>
                                </div>
                            </div>
                            <div className="grid grid-cols-2 gap-y-4 gap-x-6 text-sm">
                                <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Role</p><p className="font-semibold text-slate-900 capitalize">{activeRole}</p></div>
                                {activeRole === 'visitor' ? (
                                    <>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Contact Number</p><p className="font-semibold text-slate-900">{selectedUser.contact_number || 'N/A'}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Email</p><p className="font-semibold text-slate-900">{selectedUser.email || 'N/A'}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Presented ID</p><p className="font-semibold text-slate-900">{selectedUser.id_presented || 'N/A'}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Purpose</p><p className="font-semibold text-slate-900">{selectedUser.purpose_of_visit}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Person to Visit</p><p className="font-semibold text-slate-900">{selectedUser.person_to_visit || 'N/A'}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Reg. Date/Time</p><p className="font-semibold text-slate-900">{selectedUser.time_in ? new Date(selectedUser.time_in).toLocaleString() : '--'}</p></div>
                                        <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Exit Time</p><p className="font-semibold text-slate-900">{selectedUser.time_out ? new Date(selectedUser.time_out).toLocaleString() : '--'}</p></div>
                                    </>
                                ) : (
                                    <>
                                        {activeRole === 'student' && (
                                            <>
                                                <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Program</p><p className="font-semibold text-slate-900">{selectedUser.program_name}</p></div>
                                                <div><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Year Level</p><p className="font-semibold text-slate-900">{selectedUser.year_level}</p></div>
                                            </>
                                        )}
                                        {(activeRole === 'professor' || activeRole === 'staff') && (
                                            <>
                                                <div className="col-span-2"><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Department</p><p className="font-semibold text-slate-900">{selectedUser.department_name}</p></div>
                                                <div className="col-span-2"><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Position/Title</p><p className="font-semibold text-slate-900">{selectedUser.position_title}</p></div>
                                            </>
                                        )}
                                        <div className="col-span-2"><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Email</p><p className="font-semibold text-slate-900">{selectedUser.email || 'N/A'}</p></div>
                                        <div className="col-span-2"><p className="text-slate-500 mb-1 text-xs uppercase tracking-wider font-semibold">Contact Number</p><p className="font-semibold text-slate-900">{selectedUser.contact_number || 'N/A'}</p></div>
                                        <div className="col-span-2 pt-2"><span className={`inline-flex px-3 py-1.5 text-xs font-bold rounded-full ${selectedUser.is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>{selectedUser.is_active ? 'Active Profile' : 'Inactive Profile'}</span></div>
                                    </>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
